[build]
  command = "npm run build"
  publish = "dist/barefoot-nomad-fe"

[[redirects]]
  from = "/api/*"
  to = "http://13.126.10.191:3000/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
